### ISSUE TITLE
[TRACKER] radare2 is not as cool as PEDA

### ISSUE THREAD

**Issue by jvoisin** [radareorg/radare2#1000]
[peda](https://github.com/longld/peda) is awesome, it would be nice if radare2 could have the same functions:
- [x] aslr : ~~Show~~/set ASLR setting of the debugger
- [x] [checksec](https://github.com/radare/radare2/issues/818) : Check for various security options of binary
- [x] dumpargs : Display arguments passed to a function when stopped at a call instruction (_à la_ ollydbg)
- [x] dumprop : Dump all ROP gadgets in specific memory range
- [x] elfheader : Get headers information from debugged ELF file
- [x] elfsymbol : Get non-debugging symbol information from an ELF file
- [x] Guessing arguments to functions
- [x]  lookup : Search for all addresses/references to addresses which belong to a memory range
- [x] patch : Patch memory start at an address with string/hexstring/int
- [x]  [pattern](https://github.com/radare/radare2/issues/900) : Generate, search, or write a cyclic pattern to memory
- [x] ~~pshow : Show various PEDA options and other settings~~
- [x] ~~pset : Set various PEDA options and other settings~~
- [x]  readelf : Get headers information from an ELF file
- [x] ropgadget : Get common ROP gadgets of binary or library
- [x] ropsearch : Search for ROP gadgets in memory
- [x]  searchmem|find : Search for a pattern in memory; support regex search
- [x]  [shellcode](https://github.com/radare/radare2/issues/372) : Generate or download common shellcodes.
- [x] Tracing
  - [x] calls
  - [x] opcodes
  - [x] syscalls
- [x] vmmap : Get virtual mapping address ranges of section(s) in debugged process
- [x] xormem : XOR a memory region with a key
- [x] Dereferencing stack parts and registers, like `ecx` on [this](https://camo.githubusercontent.com/e6267dfbdf4872b6de69b1bdb25d11241a1f5a6f/687474703a2f2f726f707368656c6c2e636f6d2f706564612f6764622d706564612d636f6e746578742e706e67) screenshot.

**Comment by nootropics** [comment]
Any update on this? I LOVE radare2 but for exploit development I find myself relying on gdb-peda more :(

**Comment by radare** [comment]
What do you miss?

**Comment by radare** [comment]
Iirc the aslr thing done afaik, the dumpargs has been always working with pf, which works fine if you use cparse types, the guessing args of functions is done by current analysis, but it can be better, same for syscalls. the search for references, ranges, etc is also done, to get the ppid, uid.. Is not yet done, but should be easy by just reading /proc on linux. Maybe after release, the common shellcodes thing is done in ragg2, im missing anything? The calltracing an optracing is also done, and same for dereferencing regs from stack is also done with pxw and such.

Imho this issue is 90% solved

**Comment by nootropics** [comment]
Wow, wait what? all of that's in the latest version? The docs don't cover most of these new features from what I see

**Comment by radare** [comment]
Documentation is useless. Join the irc and ping me or just ask for how to do something here.

**Comment by nootropics** [comment]
Wow alright man, what server/nick?

**Comment by jvoisin** [comment]
#radare on freenode

By the way, feel free to help us document radare2 against @radare will. I'll be supper-happy to publish an article about exploitation on the [blog]( http://radare.today )

**Comment by radare** [comment]
the shellcodes are from ragg2, the parameters on call can be taken by signature or just pxr@esp after entering in the call, between other methods

**Comment by radare** [comment]
tracing capabilities are way more complete than in peda. and i didnt touched them for years. so i just checked the boxes

**Comment by jvoisin** [comment]
`the parameters on call can be taken by signature or just pxr@esp after entering in the call`
This should be done by default.

**Comment by radare** [comment]
Define default

**Comment by jvoisin** [comment]
Like showing the parameters in comments, when it's possible, for call, every time.

**Comment by Maijin** [comment]
@jvoisin please verify

**Comment by jvoisin** [comment]
Well, it's ghetto. I'd like to find references to a range, not search for a precise hex value.

**Comment by Maijin** [comment]
@jvoisin can you open an issue with screenshot comparing r2 /v /V and peda ?

**Comment by radare** [comment]
Rtfm thats what /V does

**Comment by jvoisin** [comment]
You're right, I only read `/v`, my bad.
