### ISSUE TITLE
META - vtable detection for C++, ObjectiveC, Dlang and Swift binaries

### ISSUE THREAD

**Issue by pinkflawd** [radareorg/radare2#17134]
- [ ] C++ structures parsing for VC++ generated binaries https://github.com/REhints/HexRaysCodeXplorer & http://www.openrce.org/articles/full_view/23
- [ ] C++ structures parsing for OS X clang C++ generates binaeis https://github.com/cocoahuke/maclook4ref
- [ ] C++ structures parsing for *nix GCC C++ generated binaries
- [ ] COM classes parsing for Windows binaries https://github.com/nektra/vtbl-ida-pro-plugin + http://blog.nektra.com/main/2013/03/27/how-to-identify-virtual-table-functions-with-the-vtbl-ida-pro-plugin/

What should be done (in C, as part of radare2):

- [x] Parsing vtables
- [x] Parsing RTTI
- [x] `av` commands to view that data
- [x] Parsing SEH
- [x] Parsing .eh_frame
- [ ] Connecting classes with their methods
- [ ] Class inheritance - nesting data structs
- [ ] Constructors and destructors autorecognition
- [ ] try/catch/finally recognition and marking
- [ ] arguments recognition
- [ ] ASCII/graphviz graph of class inheritance/structure inheritance
- [ ] Tests with sources for C++, ObjC and Swift, for radare2-regressions

See code at

-  [libr/anal/vtable.c](https://github.com/radare/radare2/blob/master/libr/anal/vtable.c)
-  [libr/anal/rtti.c](https://github.com/radare/radare2/blob/master/libr/anal/rtti.c)
-  [libr/anal/rtti_msvc.c](https://github.com/radare/radare2/blob/master/libr/anal/rtti_msvc.c)

Examples of similar features in another programs:
- https://github.com/astrelsky/Ghidra-Cpp-Class-Analyzer

-----

Attached binary is malware written in C++, lots of vtables, not detected with av command.
password is infected 

[banito.zip](https://github.com/radare/radare2/files/802015/banito.zip) password: "infected"
[2018-asplos.pdf](https://github.com/radare/radare2/files/2208556/2018-asplos.pdf)

**Comment by HoundThe** [comment]
I guess I can tick, ASCII inheritance graph with this PR https://github.com/radareorg/radare2/pull/17362

**Comment by XVilka** [comment]
See also these for extracting C++ classes information from kernelcache:
- https://github.com/0x36/ghidra_kernelcache
- https://github.com/bazad/ida_kernelcache

**Comment by trufae** [comment]
@pinkflawd r2 support for c++, swift and the whole types system has been rewritten, can you take a look at the binaries you have and provide some feedback if there's anything missing around this? thank you!
