### ISSUE TITLE
META - Console Interface improvements

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#17132]
# CLI Mode and Global

* [ ] Doc - TBD
* Tests - https://github.com/radare/radare2-regressions/blob/master/t/cmd_visual (https://github.com/radare/radare2/issues/3711)
* Commands involved - `V**`/`pdf`
* [ ] BlogPost - TBD
* .c involved:
    * libr/core/panels.c
    * libr/core/visual.c
    * libr/anal/reflines.c
    * libr/cons/cons.c
    * libr/core/disasm.c

### Enhancements

- [x] META: Autocompletion https://github.com/radare/radare2/issues/3033
- [x] Separate command line history for SDB shell https://github.com/radare/radare2/issues/7649
- [ ] Multiple windows support not accessible https://github.com/radare/radare2/issues/8829
- [x] API and commands for TABLE "widget" (like for graphs) https://github.com/radare/radare2/issues/7519
- [ ] API and commands for TREE "widget" (like for graphs) https://github.com/radare/radare2/issues/12745
- [x] Vi mode for dietline https://github.com/radare/radare2/issues/9269
- [x] Obey colorscheme for radiff2 graphs https://github.com/radare/radare2/issues/2141
- [ ] Embedded Markdown viewer https://github.com/radare/radare2/issues/11562
- [ ] Vertical split with IPython https://github.com/radare/radare2/issues/11564

### Bugs

- [ ] `Vdf`, `V_` and Vb doesn't honor CTRL+C
- [x] ^R in dietline doesnt supports repeated search https://github.com/radare/radare2/issues/3209
- [ ] Problems with `bicon` console https://github.com/radare/radare2/issues/7594
- [x] Mouse clicks trigger seemingly random actions https://github.com/radare/radare2/issues/12493

## Display

- [x] Add support for bold attribute in RCons (`ec` command) To change not only color of text group, but also its thickness
- [x] Improve disassembly reflines https://github.com/radare/radare2/issues/3670
- [ ] Context-dependent colors for comments https://github.com/radare/radare2/issues/5716
- [x] Dotted lines for conditional jumps https://github.com/radare/radare2/issues/204
- [ ] META: Better support for Unicode, RTL and BiDI https://github.com/radare/radare2/issues/2032
- [ ] Add option to choose the hex highlighting rules https://github.com/radare/radare2/issues/1784
- [ ] Support custom color palettes and non-byte sized pixel colors https://github.com/radare/radare2/issues/7638

# Visual Mode

- [ ] Two dimensional Visual mode https://github.com/radare/radare2/issues/7017
- [ ] Cursor mode (selecting lines) in ASCII/Unicode graph https://github.com/radare/radare2/issues/7248
- [x] Add a popup console "widget" https://github.com/radare/radare2/issues/8476
- [ ] Split-view visual hex diff mode for radiff2 https://github.com/radare/radare2/issues/8115
- [ ] Enhance the VE (visual color scheme editor) https://github.com/radare/radare2/issues/3692
- [x] Visual threads browser (in debug mode or inspecting coredump)  https://github.com/radare/radare2/issues/9268
- [ ] New Visual SDB Browser https://github.com/radare/radare2/issues/11979

## Visual Graph

- [x] Command/API to set particular node background https://github.com/radare/radare2/issues/8588
- [ ] Show minigraph together with the graph https://github.com/radare/radare2/issues/7182

## Visual Panel

- [x] Visual panels layout load/save option https://github.com/radare/radare2/issues/8215

**Comment by trufae** [comment]
all that stuff is done or irrelevant
