### ISSUE TITLE
Tracking progress on ##signatures

### ISSUE THREAD

**Issue by swoops** [radareorg/radare2#17546]
I have a mental list of things I want to fix, refactor or add to `r_sign`. I figured I would make it public so I could receive feedback. Some of these may be a bad idea and someone should tell me no before I get started.

## refactor/fixes
- [x] Disable by default `o`ffset signature
- [x] Fix parsing of type signatures.
- [x] ~~Simplify `t`ype signature format.~~ Found better solution
- [x] Don't re-create a new RSignItem per signature type search.
- [ ] Allow de-serialization of only needed signature types.

## new features
- [ ] Add ESIL CFG Graph signatures type.
- [ ] Efficiently find best signature file from a directory of signature files.
- [x] Diff the current functions assembly with a byte signature.
- [x] Create signature files from .a files with rasign2.

**Comment by swoops** [comment]
I am going to close this. The don't know that the last couple things should be done and I have a couple things not on this list that I am working on.
