### ISSUE TITLE
EPIC: Improve the CI

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#19687]
Right now the CI takes so much time to test all the things, it's fine somehow as long as we can cancel some jobs sometimes.

General
* [x] Automatically publish artifacts in releases
* [x] Reduce time, decide better which pipelines to run and merge some

FreeBSD
* [x] run some tests (like tcc or gperf pipelines do, not the whole testsuite?)
* [x] Dont copy back the source directory via rsync (rm -rf *)
* [ ] Create dist/freebsd package https://github.com/danrue/oneoff-pkg-create
* [x] Fix warnings in io.ptrace
* [ ] Cache somehow the vbox image? (upvote the action repo!)

Windows
* [ ] Fix race condition in meson build system
* [ ] Build may fail when not using configure;make

Fedora
* [ ] Update dist/rpm from Fedora repository
  * https://github.com/radareorg/radare2/issues/19681
* [ ] Create .rpm by adding a fedora pipeline and publish the artifact

Android
* [ ] Add builds for android kitkat (32bit)

**Comment by AH-DL** [comment]
Thanks for the attention on FreeBSD package, i will work on that list

**Comment by trufae** [comment]
We are quite good now considering freebsd is updating more frequently ans rhe only remaining bug is the meson race condition on windows but thats a known old friend. Lets close it
