### ISSUE TITLE
EPIC: RArchConfig

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#20010]
* [x] Port RReg
* [ ] Port RDebug (dbg->bits is a bitfield!!!!) R_SYS_BITS_XXX are not 8, 16, 32...
* [x] Port RPrint (https://github.com/radareorg/radare2/pull/20126)
* [ ] ~~Port RBinInfo (also have its bits/arch for subbin selection)~~

**Comment by trufae** [comment]
rdbg is not tied because it needs to control its values
