### ISSUE TITLE
EPIC: Packaging for 5.7

### ISSUE THREAD

**Issue by trufae** [radareorg/radare2#20179]
* [ ] Create PACKAGING document (f.ex: https://github.com/ifreund/waylock/blob/master/PACKAGING.md)
* [ ] Support Ubuntu via AppImage (https://docs.appimage.org/introduction/software-overview.html#ref-appimagetool)
* [ ] Support Fedora (looking at repology it seems to be pretty well updated) but dist/rpm/radare2.spec needs updating
* [ ] Haiku - needs to be updated
* [ ] Windows (winget is the official pkg manager) https://docs.microsoft.com/en-us/windows/package-manager/

**Comment by nikkej** [comment]
I could have a look over this. I have not made rpm spec which uses maven and/or ninja to build binaries but I'm very keen to learn that too as I have adequate understanding how packaging is made for rpm and deb based systems.

**Comment by nikkej** [comment]
Sorry, I meant meson, not maven...

**Comment by trufae** [comment]
Maybe good to extend this ticket to also cover iaito https://repology.org/project/iaito/versions

**Comment by trufae** [comment]
There is an rpm spec file, but as long as rpm is not a generic package like it happens with debian ones it will require a differene one for each rpm-based distro 😞

**Comment by nikkej** [comment]
That's  true. In which case rpm limitations should be mentioned  PACKAGING.md file imho. Also, should preparing and building rely on meson / ninja rather than gnu autotools in rpm (and in deb)? I was thinking shall it ease maintaining if there are fewer ways to build radare2?

**Comment by trufae** [comment]
Git will always have an odd number. The reason is because meson doesnt support rc/git/alpha/dev tags like it does acr.

theres a document describing the version numbering rules. 

If you are packaging a release the version will be always end with 0,2,4,6 or 8. Which is imho the way to to (dont package git because its not a fixed version).

the tags will only handle pair numbers, and you can use a meson oneliner or grep or ./configure -qV to get the version before compiling. If you wait some days i will release 5.7.4 in about a week
