### ISSUE TITLE
META - Infrastructure

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#3251]
# Build System

## CI - General 

- [x] Improve CI (move to the `buildbot`?)

## CI - Tests

- [ ] Enable ASAN on a non-blocking suite
- [ ] Only one report message displayed at the end

-> See Radare2-regressions repository for more issues

## CI - Builds

- [ ] asmjs builds
- [ ] NetBSD build (ask [ryoshu](https://github.com/krytarowski) or @sevan  about this)
- [ ] Producing Static bins @XVilka 
- [x] Add support of building radare2 using clang-cl (https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Building_Firefox_on_Windows_with_clang-cl && http://sourceforge.net/projects/clangonwin/files/MsvcBuild/3.7/)
- [ ] WebAssembly build target (https://github.com/WebAssembly/binaryen#cc-source--asm2wasm--webassembly)

# Code Quality

## Code Review

- [ ] Writing Coverity modelling file for better analysis http://scan.coverity.com/models
- [ ] Run infer

## Indentation

(except what its not from us (gnu, grub, ...)) we want to autoindent all *.c under libr and binr . The plan is the following:

* [ ] Use uncrustify (seems like it got better than clang-format recently) and we miss some functionalities still
* [ ] Report all missing features in clang-format and uncrustify to the respective projects
* [ ] Remove all the sed/perl hacks in sys/indent.sh
* [ ] Add more files into the sys/indent-whitelist.sh
* [ ] Run sys/indent-whitelist.sh on every commit to ensure 

The process of re-indenting consists in:

* Review the output of `sys/indent.sh -u libr/core/foo.c`
* If the output looks good use the `-i`

If the output doesn't looks good:

* Improve uncrustify.cfg
* Improve indent.sh
* Improve the problematic .c to make it indent properly

**Comment by Maijin** [comment]
What about switching FROM curent:
* TESTS=anal.arm
* TESTS=anal.java
....

TO:

* TESTS=GCC/LINUX
* TESTS=GCC/OSX
* TESTS=CLANG/LINUX
* TESTS=CLANG/OSX

That would ease the display and allow more possibility

**Comment by radare** [comment]
Why shouting? This wont give you the reason

**Comment by Maijin** [comment]
@radare ? Sorry, this was not meant to be a shout :p

**Comment by dequis** [comment]
>give you the reason

Hahah, that idiom doesn't exist in english, pancake.

**Comment by Maijin** [comment]
@dequis but exist in french :)

**Comment by radare** [comment]
pls guise, do something here

**Comment by Maijin** [comment]
@sevan could look at the netbsd CI ^

**Comment by sevan** [comment]
Sure, what's the requirements?

**Comment by radare** [comment]
@sevan to build every commit of r2 in a netbsd, maybe in a VM or so.. https://hub.docker.com/r/anyakichi/netbsd-builder/  this can be handy to integrate in radare2-release repo for example

**Comment by XVilka** [comment]
@sevan also in the long run (in a couple months, I hope) I'm going to replace our CI (ci.rada.re) server completely, would be nice to setup netbsd vm too.

**Comment by krytarowski** [comment]
I've not been following r2 in a while. I know how to attach to python buildslave. I'm using it for LLVM+Clang+LLDB CI. Java and docker are out of my control.

**Comment by sevan** [comment]
It would be cool if you could work out what the CI requires & state that, leaving the implementation on the client side where builds are performed (if nothing is currently prepared).
Trying to work out what the [docker script](https://github.com/anyakichi/docker-netbsd-builder/blob/master/Dockerfile) is actually trying to do, I don't think it would ever work because a) there is no NetBSD docker support b) there is no apt-get on NetBSD :)

**Comment by Maijin** [comment]
@sevan just need builds essentials make, gcc git and web-connexion.
Then:
```
  - git clone https://github.com/radare/radare2
  - git clone --depth 1 `doc/repo REGRESSIONS`
  - ./configure --prefix=`pwd`/install > /dev/null
  - make -s -j2 > /dev/null
  - make install > /dev/null
  - export NOOK=1
  - export NOREPORT=1
  - cd radare2-regressions
  - VERBOSE=1 make -k all
  - make unit_tests
```

**Comment by XVilka** [comment]
No gerrit needed, since Github PRs are used.

**Comment by XVilka** [comment]
Not related to this particular release.

**Comment by XVilka** [comment]
Should we close this? Seems most of its either done or irrelevant. The only missing points are NetBSD builds (WIP by SourceHut) and reformatting the code, which we track separately.
cc @radare

**Comment by radare** [comment]
ok
