### ISSUE TITLE
Move issues from Todo.md to github issues and kill it

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#5424]
Move issues from Todo.md to github issues and kill it:

https://github.com/radare/radare2/blob/master/TODO.md
#0) I've gathered everything in here https://hackmd.io/GYQwHALADApgxlAtAZmANgIyIjWiBGATMAOyJpRr5gwCcJAJsAKwZA==
#1) Review and create issues on them

**Comment by radare** [comment]
agree

**Comment by DanTheColoradan** [comment]
Wow. There was a lot there.

I split it into individual sections as I don't believe there is enough information to have them each as their own issue.

The next step (as I imagine it) is to create individual issues for each item once there is enough info. Then, just check it off the original list and edit it to have a reference to the new issue. Or if they are already done / not needed anymore, just strike out that item.

I can submit a pull request to remove the TODO.md if you would like.

**Comment by Maijin** [comment]
wow @radare should review, also @DanTheColoradan there are other TODO.md inside the repo maybe you could also kill them

**Comment by DanTheColoradan** [comment]
K

**Comment by DanTheColoradan** [comment]
- [ ] libr/cons/TODO
- [ ] libr/search/TODO
- [ ] libr/syscall/TODO
- [ ] shlr/grub/TODO

**Comment by radare** [comment]
git grep TODO will show more but dont be that exhaustive. Having yhe todo stuff in the code is handier than having to check the github website

**Comment by radare** [comment]
Al those new issues are completely useless. I dont understand why are you grouping them or even creating new issues without checking if its already done or discussing

**Comment by DanTheColoradan** [comment]
So you are suggesting leaving the TODO.md? Or creating an issue for each item?

I was attempting to get rid of the TODO.md like this issue states without creating a bunch of empty issues.

**Comment by DanTheColoradan** [comment]
I don't have enough knowledge of what's been done to figure out which in TODO.md shouldn't turn into issue.

**Comment by DanTheColoradan** [comment]
I figured it was easier to group them how they are grouped in the TODO.md and then discuss them like you suggest in those respective sections.

**Comment by DanTheColoradan** [comment]
I agree they should be an issue each. But we need a starting point to figure out what to keep and what to get rid of and we can't do that inside TODO.md. Discussing all of it in one thread seems like way too much as well.

So what I'm suggesting is, even though the sections aren't perfect, we start with them anyway. We do as you said and discuss the items and make issues of each with better detail.

If you feel you have a better plan than that, let me know :)

**Comment by radare** [comment]
Yep github issues is a better place to discuss them and review than a plain text file

**Comment by Maijin** [comment]
I've gathered everything in here https://hackmd.io/GYQwHALADApgxlAtAZmANgIyIjWiBGATMAOyJpRr5gwCcJAJsAKwZA==

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
i'll do some cleanup if im in the mood before 1.0 but its not really a prio so moving to 1.1

**Comment by radare** [comment]
(if anyone else wanna help on this)

**Comment by InsidiousMind** [comment]
Hey! I'll take this up as my first contribution. It's pretty simple to do and i'm just looking over the codebase and getting used to it so I think this would be a good opportunity.

**Comment by Maijin** [comment]
Well if nobody care anymore about the contents of those we should close this and forget about them.

**Comment by radare** [comment]
I do

**Comment by ret2libc** [comment]
Closing. I can't find that TODO.md anymore. And I think the Issues page on github is already *full* of TODOs and ideas :)
