### ISSUE TITLE
META - Portable Executable

### ISSUE THREAD

**Issue by Maijin** [radareorg/radare2#921]
# All Portable Executables

## Related

* [ ] Doc - TBD
* Tests - https://github.com/radare/radare2-regressions/tree/master/t.formats/pe
* Commands involved - N/A
* [ ] BlogPost - TBD
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/bin/p/bin_pe.c

## General Information

- [ ] Add DLL Characteristics in `iI`, `iIj` (Already parsed in SDB) #6785 Or in `iH` , `iHj` https://github.com/radare/radare2/issues/6759
- [ ] VTABLE detection for MSVC https://github.com/radare/radare2/issues/6851
- [x] Add authentihash and authentihash check in `it` and `itj`

## R_BIN Enhancement

 radare2-regressions files that are not properly parsed by r2 currently:
- [ ] d_resource.dll
- [ ] d_tiny.dll
- [ ] dosZMXP.exe
- [ ] exe2pe.exe
- [ ] no0code.exe

## Analysis

- [ ]  detect and rename the elements/structures accordingly. (See all the +ms_exc.registration.TryLevel etc...) see http://pastebin.com/aLrkiwuM
[reversing-demo.zip](https://github.com/radare/radare2/files/801155/reversing-demo.zip)

## Resources

- [ ] Add/remove/modify/dump Resources `rabin2 -O` && `iO`

## Import/Export Table

- [ ] Ability to move the import table `rabin2 -O` && `iO`
- [ ] Ability to add/remove import/export library (with prior checks to see if possible) `rabin2 -O` && `iO`
- [ ] Ability to add/remove function to a library (with prior checks to see if possible) `rabin2 -O` && `iO`
- [ ] Ability to dump a process and reconstruct/manipulate IAT (ollydump + IMPrec tool / x64dbg) (https://github.com/OALabs/PyIATRebuild/blob/master/pyiatrebuild.py)
- [ ] Add PE unmapper https://github.com/hasherezade/malware_analysis/tree/master/pe_unmapper {as a r2e module}
- [ ] Implement the Windows API import recovery functionality shown in the apiscout: https://github.com/danielplohmann/apiscout -- (API import recovery: http://byte-atlas.blogspot.de/2017/04/apiscout.html) (https://github.com/danielplohmann/apiscout/issues/1)
- [ ] Add imphash https://github.com/Neo23x0/ImpHash-Generator  {As a r2e module}

## Rich Header

- [x] https://github.com/radare/radare2/issues/12889

## Debug Informations

- [ ] Display debug file info: age

## Sections

- [ ] Add sections headers into the `pf` output
- [ ] Ability to add/resize/move/... sections

## SEH/VEH

- [ ] SEH Parser for PE 32 bits see http://blog.davidegrayson.com/2016/02/windows-32-bit-structured-exception.html
- [ ] SEH Parser for PE 64bits see https://github.com/tandasat/scripts_for_RE/blob/master/parse_x64_SEH.py

# Specific Language Portable Executables

## .NET

- [ ] Load and display .NET PE information in `iI,iIj` 
- http://www.ntcore.com/files/dotnetformat.htm
- http://www.reddit.com/r/ReverseEngineering/comments/2cw2o2/pe_net_that_is_not_pe_net/
- https://blog.cylance.com/you-me-and-.net-guids
See preliminary step - https://github.com/radare/radare2/issues/6771

## Others

- [ ] A way to handle [RFG](http://redplait.blogspot.ru/2017/03/ida-plugin-for-rfg-fixups-processing.html)
- [ ] A way to handle [AutoIT](https://www.autoitscript.com/site/autoit/) PE
- [ ] A way to handle [AutoHotKey](http://www.autohotkey.com/) PE
- [ ] A way to handle Delphi  like it is done with this ida and associated plugins idr, idc scripts, https://github.com/nccgroup/pythia etc...
- [x] A way to handle VB5/VB6  - fixed by @aaSSfxxx https://github.com/aaSSfxxx/r2_scripts/blob/master/vb_analysis.py
- [ ] Add the VB helper script in Core - https://github.com/radare/radare2/issues/12311

**Comment by Maijin** [comment]
With pf on pe32 the command should be: `pf.petimeDateStamp_nt_image_headers32.timeDateStamp @ pe_nt_image_headers32`

**Comment by radare** [comment]
Ping @hyask

**Comment by Hyask** [comment]
pf.pe_nt_image_headers32.fileHeader.timeDateStamp

that thing works for me, with some bugs, but the information is there...

**Comment by Maijin** [comment]
Yes It works but it displays a lot of garbage : http://radare.tv/a/77

**Comment by Hyask** [comment]
I know, I'll fix that asap

**Comment by XVilka** [comment]
@Hyask ping?

**Comment by Maijin** [comment]
Timestamp is available in `ik` now, but should be available in `i`

**Comment by Maijin** [comment]
Some of those tasks are easy to do

**Comment by XVilka** [comment]
Added this one https://github.com/radare/radare2/issues/2416

**Comment by Maijin** [comment]
@XVilka yes :+1:

**Comment by Maijin** [comment]
Resources have been extracted but there are no way to display them with a dedicated command, what a shame :confused:

**Comment by Maijin** [comment]
To get the certificate one-liner: 
```
pr `pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[4].size @ pe_nt_image_headers32` @ `pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[4].virtualAddress @ pe_nt_image_headers32`+8 > pe_certificate ; !openssl pkcs7 -inform DER -print_certs -text -in pe_certificate
```

**Comment by Maijin** [comment]
For VB some pf structure may be useful as well, I'm doing some

**Comment by timofonic** [comment]
Any news for this GSoC? Can this be interesting for rewritten engines like ScummVM/RogueVM and not need to use the expensive IDA Pro?

There could be other interoperability purposes too, there many proprietary file formats everywhere in proprietary software for Microsoft Windows family and most useful tools like IDA are quite expensive.

NE support would be nice too :) 
https://github.com/radare/radare2/issues/2730

**Comment by Maijin** [comment]
@timofonic Hey ! Feel free to help on those issues, see some people are adding some of the features https://github.com/radare/radare2/pull/4149 so is WIP

**Comment by Maijin** [comment]
Btw if the question is just, does it supports PE, yes it definitely does already since a long time.

**Comment by timofonic** [comment]
@Maijin That's nice! Thanks!

Unfortunately, I'm not yet enough skilled to be considered a developer. I'm just doing little tests these days, but nothing serious.

Anyway, it would be very nice to have an alternative to IDA Pro. Now the GUI is another issue you're quite aware too :D

**Comment by Maijin** [comment]
@timofonic Btw if the question is just, does it supports PE, yes it definitely does already since a long time.

**Comment by timofonic** [comment]
@Maijin 

Sorry for my bad explanation. I did mean about the missing PE features.

Anyway...
Are there some side by side comparison with other software like IDA Pro and... others (are there?)?

**Comment by lionaneesh** [comment]
Hey I am working on PE's CRC extraction and check. Would adding it as an info command work?

This is what it looks like right now:
```
[0x00401188]> iC
File Checksum: 0000012c
Computed Checksum: fe454d60
```

**Comment by 0x2Adr1** [comment]
hi guys, I am currently working on:

- [x] the version info of ELF and Mach-O binaries (PE was already merged)
- [x] Extract/Dump Resources (any idea of a good command shortcut for this? "iR [file]" maybe)

**Comment by radare** [comment]
Yes this looks good. Right now ive been saving this in sdb, it is used for dex, and when loading a dex it shows the current hash and prints an r2 command to calculate the hash.

I think this info is already saved in sdb for PE too.. Or at least it should. But its cool to have a top level command for this rather than messing with sdb

**Comment by Maijin** [comment]
Awesome \o/

**Comment by radare** [comment]
To extract dump respueces use the -O (uppercase O) there are some dumping/manipulation conmands there already

**Comment by radare** [comment]
We should probably make iO accessible from r2, not just rabin2 from shell

**Comment by timofonic** [comment]
Hello.

I'm not a developer, just a wannabe that's struggling at electronics right
now. But I consider reverse engineering very interesting in the digital
preservation and interoperability ways. I consider Document Liberation
Project a very amazing work, I hope this happens in other sectors like
Electronic Design Automation (this is awful, there are zillions of file
formats and even the expensive competitors have important issues importing
the other formats!) and other sectors with file formats that seriously
favours the very negative vendor lock-in).

Are there plans to collaborate with projects potentially interested in your
tools? I only know about those related to games such as ScummVM. Maye they
could replace IDA Pro with your tools. The reverse engineer games from old
up to Windows platforms, mostly in 2D. There can be other candidates such
as GemRBG, RogueVM and ResidualVM too :D

I would really love to see KiCad, QUCS, Sigrok and gEDA to someday have
accurate file format importing capabilities and able to import projects
from proprietary tools to FOSS ones.

You know: Eat your own dog food. Maybe the use of more projects to achieve
certain goals could stimulate the development and bugfixing ;)

Kind regards.

**Comment by XVilka** [comment]
@timofonic good to hear, not sure how this does relate to this particular bug though. You're welcome on our #radare IRC channel to discuss such things, or to corresponding Telegram channel.

**Comment by amareshkumar** [comment]
these are all for either PE or ELF file type! what about mach-o binaries. what should i do to know who has signed any unknown mach-o binary. any clues please w.r.t. C++ programs or something similiar

**Comment by XVilka** [comment]
https://github.com/radare/radare2/commit/5c98293b20fd02288c724ee8b52ae2541f850716 - can be useful for implementing some of those.

**Comment by XVilka** [comment]
So now the biggest priority of improving Windows support is to fix all broken tests and enable depending on them on AppVeyor: ` OK 5345 BR  872 XX 1744 FX    0`

**Comment by XVilka** [comment]
@GustavoLCR @pelijah FYI
